### ISSUE TITLE
how to setup api_key for each user?

### ISSUE THREAD

**Issue by kaixinbuyu** [appbaseio/arc#37]
I have some text Corpus  indexed by es.
I want to publish some es query API on the public internet.
Each user use an api_key to invoke the API,rate-limited by monthly query count.

Is arc,acl support this "api_key" way,or how to set up auth,acl,jwt to archive this? Is there any example/document related to this?
I'm a bit confused with the module "Permission","Authentication","ACLs","JWT Key Loading through HTTP".

**Comment by siddharthlatest** [comment]
@kaixinbuyu You can use the Permissions endpoints to create an API_Key for each end-user of your application. Right now, we only have the [API ref doc](https://arc-api.appbase.io/?version=latest).

If you are considering JWT and RBAC, then the mapping can be one API_Key per unique user role instead of one API_Key for each user.

This is the sequence I would recommend:

1. For using JWT and RBAC features, [set the public key](https://arc-api.appbase.io/?version=latest#491c0f76-0cb1-4e14-b3e9-9831758be39f),
2. [Create Permission by Role](https://arc-api.appbase.io/?version=latest#441f1f65-bbcc-467a-88fb-c14926be7036).

Now make sure your JWTs are signed by the corresponding private key (for which you set the public key in 1.) and have the role claim set to one of the values you have defined in step 2. That's all.

**Comment by kaixinbuyu** [comment]
I'll have a try at once.thanks for your guide!
